---
fabric_name: evpn_symmetric
bgp_asn_prefix: 651
id: 9999
vxlan_local_loopback: "172.29.9.{{ id }}/32"
vxlan_anycast_loopback: "172.29.1.{{ vxlan_anycast_id | default( id ) }}/32"
eth0_subnet: 172.29.10.0/24
eth0_ip: "{{ eth0_subnet | nthhost( eth0_id | default( id ) ) }}/{{ eth0_subnet | ipaddr('prefix') }}"
