---
backup:
  path: "../inventories/{{ fabric_name }}/config/{{ inventory_hostname }}"
  files:
    - "/etc/network/interfaces"
    - "/etc/frr/frr.conf"
    - "/etc/frr/daemons"
dns:
  domain: cumulusnetworks.com
  search_domain:
    - cumulusnetworks.com
  servers:
    ipv4:
      - "1.1.1.1"
      - "8.8.8.8"
    vrf: mgmt
snmp:
  addresses:
    - "{{ eth0_ip | ipaddr('address') }}@mgmt"
    - "udp6:[::1]:161@mgmt"
  rocommunity:
    - public
    - private
syslog:
  servers:
    - 192.168.200.1
ntp:
  timezone: Africa/Kigali
  server_ips:
    - 0.cumulusnetworks.pool.ntp.org
    - 1.cumulusnetworks.pool.ntp.org
    - 2.cumulusnetworks.pool.ntp.org
    - 3.cumulusnetworks.pool.ntp.org
ssh:
  motd: |
    #########################################################
    Successfully logged in to: {{ inventory_hostname }}
    #########################################################
  banner: |
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Authorized Users Only!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
tacacs:
  vrf: mgmt
  secret: tacacskey
  server_ips:
    - 172.29.3.1
  users:
    - name: guest
      password: password
      group: basics
    - name: admin
      password: 1r3mb0Cumu1u5
      group: admins
  groups:
    # admin group can do anything on network gear
    - name: admins
      priv_level: 15
    # basic group can run show commands and diagnostics but not change system configuration
    - name: basics
      priv_level: 1

