---
vlan20_subnet: "172.29.2.0/24"
vlan30_subnet: "172.29.3.0/24"
vlan40_subnet: "172.29.4.0/23"
vlan70_subnet: "172.29.7.0/24"

mac_prefix: 00:00:00:00:00

vlan20:
  name: vlan20
  id: 20
  vrf: ADMIN
  address:
    - "{{ vlan20_subnet|nthhost( id+1 ) }}/{{ vlan20_subnet|ipaddr( 'prefix' ) }}"
  address_virtual:
    - "{{ mac_prefix }}:20 {{ vlan20_subnet|nthhost( 1 ) }}/{{ vlan20_subnet|ipaddr( 'prefix' ) }}"
vlan30:
  name: vlan30
  id: 30
  vrf: DMZ
  address:
    - "{{ vlan30_subnet|nthhost( id+1 ) }}/{{ vlan30_subnet|ipaddr( 'prefix' ) }}"
  address_virtual:
    - "{{ mac_prefix }}:30 {{ vlan30_subnet|nthhost( 1 ) }}/{{ vlan30_subnet|ipaddr( 'prefix' ) }}"
vlan40:
  name: vlan40
  id: 40
  vrf: DB
  address:
    - "{{ vlan40_subnet|nthhost( id+1 ) }}/{{ vlan40_subnet|ipaddr( 'prefix' ) }}"
  address_virtual:
    - "{{ mac_prefix }}:40 {{ vlan40_subnet|nthhost( 1 ) }}/{{ vlan40_subnet|ipaddr( 'prefix' ) }}"      
vlan70:
  name: vlan70
  id: 70
  vrf: APP
  address:
    - "{{ vlan70_subnet|nthhost( id+1 ) }}/{{ vlan70_subnet|ipaddr( 'prefix' ) }}"
  address_virtual:
    - "{{ mac_prefix }}:70 {{ vlan70_subnet|nthhost( 1 ) }}/{{ vlan70_subnet|ipaddr( 'prefix' ) }}"

